const {Schema, default:mongoose} = require("mongoose")
const seller = new Schema({
    googleId:{
        type:Schema.Types.String,
        require:true
    },
    name:{
        type:Schema.Types.String,
        require:true
    },
    email: { type: String, required: true }, 
    logo:{
        type:Schema.Types.String,
        require:true
    },
    address:{
        type:Schema.Types.String,
        require:true
    },
    mobileNo:{
        type:Schema.Types.String,
        require:true
    },
    verifiedSupplier:{
        type:Schema.Types.Boolean,
        require:true
    },
    experience:{
        type:Schema.Types.Number,
        require:true
    },
    onlineStatus:{
        type:Schema.Types.Boolean,
        require:true
    },
    views:{
        type:Schema.Types.Number,
        require:true
    },
    rating:{
        type:Schema.Types.Number,
        require:true
    },
    trustSEAL:{
        type:Schema.Types.Boolean,
        require:true
    },
    leadingSupplier:{
        type:Schema.Types.Boolean,
        require:true
    },
    verified:{
        type:Schema.Types.Boolean,
        require:true
    },
    details:{
        type:Schema.Types.String,
        require:true
    },
    reviews:[{
        name:{
            type:Schema.Types.String
        },
        comment:{
            type:Schema.Types.String
        },
        rating:{
            type:Schema.Types.Number
        }
    }],
    banner:{
        type:Schema.Types.String
    },
    established:{
        type:Schema.Types.Number,
        require:true
    },
    numberOfEmployees:{
        type:Schema.Types.Number,
        require:true
    },
    natureOfBusiness:{
        type:Schema.Types.String,
        require:true
    },
    legalStatus:{
        type:Schema.Types.String,
        require:true
    },
    annualTurnover:{
        type:Schema.Types.Number,
        require:true
    },
    workingDays:{
        type:Schema.Types.String,
        require:true
    },
    website:{
        type:Schema.Types.String,
        require:true
    },
    responseRate:{
        type:Schema.Types.Number
    },
    transactions:{
        type:Schema.Types.Number
    },
    country:{
        type:Schema.Types.String,
        require:true
    }
})
const sellerModel = mongoose.models.seller || mongoose.model("seller",seller)
module.exports = sellerModel